<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Wall extends Model
{
    use HasFactory;

    protected $fillable = [
        
        'additionalDatas',
        'courses',
        'name',
        'wall_material',
        'wall_material_value',
        'trade',
        'shape',
        'gable_value',
        'slope_value',
        'rise_drop',
        'rise_value',
        'drop_value',
        'wall_height',
        'finish_floor',
        'top_of_footing',
        'effective_foundation_height',
        'total_wall_height',
        'wall_length',
        'total_wall_length',
        'wall_structure_thickness',
        'total_square_area',
        'total_cubic_area',
        'wall_square_units',
        'wall_cubic_units',
        'coping_material',
        'coping_material_quantity',
        'coping_material_total',
        'coping_material_total_units',
        'anchor_material',
        'anchor_spacing',
        'anchor_quantity',
        'anchor_total',
        'top_wall_material',
        'coping_wall_side',
        'total_anchor_coping',
        'total_anchor_coping_units',
        'bars_per_ton',
        'grout_fill_material',
        'rebar_spacing',
        'additional_spacing',
        'total_spaces_filled',
        'rebar_lift_spaces',
        'total_lifts',
        'vertical_rebar_overlap',
        'rebar_lf_pr_space',
        'bars_per_space',
        'vertical_rebar_total',
        'lft_rebar_per_ton',
        'vertical_total_rebar_tons',
        'vertical_rebar_positioner',
        'vertical_postioner_per_total',
        'vertical_postioner_other_total',
        'vertical_grout_material',
        'vertical_grouted_area',
        'remaining_area',
        'vertical_fill_remaining',
        'sq_fill_mat_per_cy',
        'total_grout_mat',
        'total_remaining_mat',
        'control_material',
        'control_spacing',
        'control_rod',
        'control_rod_side',
        'half_block_material',
        'control_total_cj_spaces',
        'control_total_cj_material',
        'control_total_cj_material_ea',
        'control_total_caulking_material',
        'control_total_caulking_material_ea',
        'control_total_sq_ft',
        'total_half_unit',
        'note',
        'half_block_lf_unit',
        'half_block_sq_unit',
        'half_block_length',
        'material_height',
        'material_width',
        'material_length',
        'wall_material_unit',
        'wall_material_square_unit',
        'wall_material_cubic_unit',
        'coping_material_height',
        'coping_material_width',
        'coping_material_length',
        'coping_material_unit',
        'user_id',
        'project_id'
    ];

    protected $casts = [
        'additionalDatas' => 'array',         
        'courses' => 'array',
        'effective_foundation_height' => 'integer',
        'total_wall_height' => 'integer',
        'total_square_area' => 'integer',
        'total_cubic_area' => 'integer',
        'total_spaces_filled' => 'integer',
        'half_block_length' => 'float',
        'material_height' => 'integer',
        'material_width' => 'integer',
        'material_length' => 'integer',
        'wall_material_cubic_unit' => 'float',
        'coping_material_height' => 'integer',
        'coping_material_width' => 'integer',
        'coping_material_length' => 'integer',
        'user_id' => 'integer',
        'project_id' => 'integer'
    ];
}